name: feature-and-test
on:
  push:
    branches:
      - develop
jobs:
  init-infrastructure:
    runs-on: ubuntu-latest
    env:
      AWS_SECRET_ACCESS_KEY: ${{ secrets.R2G_AWS_SECRET_ACCESS_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.R2G_AWS_ACCESS_KEY_ID }}

    steps:
      - uses: hashicorp/setup-terraform@v1
      - uses: actions/checkout@v2
      - run: terraform init
        working-directory: ./terraform/feature-branch-and-test
      - run: terraform apply -no-color -var bucket_name=mzborowski-r2g-develop -auto-approve
        working-directory: ./terraform/feature-branch-and-test

  build-gatsby:
    runs-on: ubuntu-latest
    needs: init-infrastructure
    steps:
      - run: sudo apt-get -y install curl
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm install
      - run: npm install -g gatsby-cli
      - run: gatsby build
      - uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: 'mzborowski-r2g-develop'
          AWS_ACCESS_KEY_ID: ${{ secrets.R2G_AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.R2G_AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: 'us-east-1'   # optional: defaults to us-east-1
          SOURCE_DIR: 'public'      # optional: defaults to entire repository

