name: learn-github-actions
on: [push]
jobs:
  build-gatsby:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get -y install curl
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - run: npm -v
      - run: node -v
      - run: npm install -g gatsby-cli
      - run: ls -la
      - run: gatsby build


